version: '3.3'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    deploy:
      replicas: 1
    volumes:
      - source: etcd-certs
        target: /etc/ssl/certs
    command:
      - "-name=etcd0"
      - "-advertise-client-urls=http://etcd:2379"
      - "-listen-client-urls=http://0.0.0.0:2379"
      - "-initial-advertise-peer-urls=http://etcd:2380"
      - "-listen-peer-urls=http://0.0.0.0:2380"
      - "-initial-cluster-token=etcd-cluster-1"
      - "-initial-cluster=etcd0=http://etcd:2380"
      - "-initial-cluster-state=new"
  ip-report:
    image: bluemir/zumo-ip-report
    deploy:
      labels:
        traefik.port: 9000
      replicas: 1
    networks:
      - proxy
networks:
  proxy:
    external: true
