version: '3.5'
services:
  docker-api-proxy:
    # basic docker proxy with basic auth
    image: bluemir/docker-api-proxy
    deploy:
      replicas: 1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "12376:2376"
  gluster-fs:
    # TODO for remote volume
    image: fedora
    deploy:
      mode: global
    command: ["tail", "-f", "/etc/hosts"]
  plugin-install:
    # TODO docker volume plugin install
    image: fedora
    deploy:
      mode: global
    command: ["tail", "-f", "/etc/hosts"]
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command:
      - "--docker.swarmMode"
      - "--docker.domain=home.blumir.me"
      - "--docker.watch"
      - "--api"
    networks:
      - proxy
configs:
  docker-proxy-conf:
    file: system/docker-proxy.conf
  docker-proxy-auth:
    file: system/.htpasswd
networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
