version: '3.5'
services:
  docker-api-proxy:
    # docker api proxy with AuthN/AuthZ
    image: bluemir/docker-api-proxy:v1
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
    environment:
      AUTHN: "token:${TOKEN}"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "2376:2376"
  gluster-fs:
    # TODO for remote volume
    image: fedora
    deploy:
      mode: global
    command: ["tail", "-f", "/etc/hosts"]
  plugin-install:
    # TODO docker volume plugin install
    image: fedora
    deploy:
      mode: global
    command: ["tail", "-f", "/etc/hosts"]
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command:
      - "--docker.swarmMode"
      - "--docker.domain=home.blumir.me"
      - "--docker.watch"
      - "--api"
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
